"""test

Revision ID: 94a35d78397c
Revises: 
Create Date: 2024-09-27 16:14:53.855899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94a35d78397c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("folder_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("channel_name", sa.String(), nullable=False),
        sa.Column("channel_stats", sa.String(), nullable=False),
        sa.Column("access_hash", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "folders",
        sa.Column("folder_id", sa.String(), nullable=False),
        sa.Column("folder_title", sa.String(), nullable=False),
        sa.Column("folder_status", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("folder_id"),
    )
    op.create_table(
        "signals",
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("channel_name", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("coin", sa.String(), nullable=False),
        sa.Column("trend", sa.String(), nullable=False),
        sa.Column("tvh", sa.String(), nullable=False),
        sa.Column("rvh", sa.String(), nullable=False),
        sa.Column("lvh", sa.String(), nullable=False),
        sa.Column("targets", sa.String(), nullable=False),
        sa.Column("stop_less", sa.String(), nullable=False),
        sa.Column("leverage", sa.String(), nullable=False),
        sa.Column("margin", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "testing_signals",
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("channel_name", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("coin", sa.String(), nullable=False),
        sa.Column("trend", sa.String(), nullable=False),
        sa.Column("tvh", sa.String(), nullable=False),
        sa.Column("rvh", sa.String(), nullable=False),
        sa.Column("lvh", sa.String(), nullable=False),
        sa.Column("targets", sa.String(), nullable=False),
        sa.Column("stop_less", sa.String(), nullable=False),
        sa.Column("leverage", sa.String(), nullable=False),
        sa.Column("margin", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testing_signals")
    op.drop_table("signals")
    op.drop_table("folders")
    op.drop_table("channels")
    # ### end Alembic commands ###
